# Use this environment to run `detection/run_tf_detector*.py`

name: cameratraps-detector

dependencies:
- python>=3.5, <=3.7.6
- nb_conda_kernels
- ipykernel
- tensorflow>=2.0
- tqdm
- jsonpickle
- Pillow>=5.3.0
- humanfriendly
- numpy
- matplotlib
- nb_conda_kernels
- ipykernel
- opencv
- requests

# the `nb_conda_kernels` and `ipykernel` packages are installed so that we
# can use Jupyter Notebooks with this environment as a kernel