# conda activate cameratraps-api-task-management
#
# conda env update --name cameratraps-api-task-management --file environment-api-task-management.yml
name: cameratraps-api-task-management

dependencies:
- python>=3.6   # known-compatible: 3.7
- ipykernel     # known-compatible: 5.1.4
- humanfriendly # known-compatible: 8.1
- matplotlib    # known-compatible: 3.1.3
- pip           # known-compatible: 20.0.2
- scikit-learn  # known-compatible: 0.22.1
- tqdm          # known-compatible: 4.45.0
- pandas        # known-compatible: 1.0.3
- Pillow        # 7.0.0
- jsonpickle    # known-compatible: 1.3
- requests      # known-compatible: 2.23.0
- pip:
  - azure-storage-blob>=12.3.0 # known-compatible 12.3.0
  - clipboard                  # known-compatible 0.0.4
