# Conda environment file for running the batch API.
#
# conda activate cameratraps-batch-api
#
# conda env update --name cameratraps-batch-api --file environment-batch-api.yml --prune

name: cameratraps-batch-api

dependencies:
- python>=3.6
- nb_conda_kernels
- humanfriendly
- requests
- flask>=1.1.0  # known-compatible Flask 1.1.2, Werkzeug 1.0.1
- gunicorn
- tqdm  # required by sas_blob_utils.py
- pip
- pip:
  - azure-storage-blob>=12.3.0  # known-compatible 12.7.1
  - azure-batch>=4.0.0    # known-compatible 10.0.0
  - azure-cosmos  # known-compatible 4.2.0
  - azure-appconfiguration  # known-compatible 1.1.1
